POST http://localhost:5000/api/reviews
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InphcnkiLCJpZCI6IjYzNzM0ZDcxMGRlYjg4YjA5MGJjYjkzYiIsImlhdCI6MTY2ODUwMTM5NiwiZXhwIjoxNjY4NTA0OTk2fQ.XQ8qVR6lDA4UfMKo-VJJy_CxYKlOEk0u3YPp_2Inr8s

{
    "bookTitle": "hobbit",
    "author": "tolkien", 
    "reviewTitle": "good book", 
    "likes": 1,
    "dislikes": 4
}